ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;
ALTER TABLE compilations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;

DELETE FROM event_comment CASCADE;
DELETE FROM comments CASCADE;
DELETE FROM requests CASCADE;
DELETE FROM compilation_event CASCADE;
DELETE FROM events CASCADE;
DELETE FROM compilations CASCADE;
DELETE FROM users CASCADE;
